"""Port the ARD / plan / spec code from rtfreporter's feat/474 branch into tflspec.

Re-runnable: it reads the files straight from the rtfreporter git branch
(`git show <ref>:<path>`) and overwrites the tflspec copies, so the port can be
repeated against a newer commit while both copies exist.  feat/474 is frozen
during that period; fixes go to tflspec.

    python dev/port-from-rtfreporter.py [ref]     # default: origin/feat/474-ard-experimental
"""
import os
import re
import subprocess
import sys

RTFR = "C:/Yrepo/rtfreporter"
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REF = sys.argv[1] if len(sys.argv) > 1 else "origin/feat/474-ard-experimental"

# Every export that moves.  `rtfreporter::<name>` for these becomes
# `tflspec::<name>` (generated code, examples, docs); every other
# `rtfreporter::` (as_rtftables, round_num, ...) stays.
MOVED = [
    "ard_pull", "ard_keys", "ard_normalize", "ard_overall", "ard_spread",
    "ard_template", "ard_cells",
    "table_spec", "table_spec_template", "read_table_spec", "write_table_spec",
    "read_report_spec", "rtf_report", "report_path",
    "rtf_plan", "plan_cells", "plan_levels", "plan_labels", "plan_digits",
    "plan_fmt", "plan_stub", "plan_cell_style", "plan_paginate_group",
    "plan_row_group", "plan_hide", "plan_sort", "plan_blanks",
    "plan_paginate_rows", "plan_style", "plan_col_header",
    "plan_paginate_cols", "plan_titles", "plan_footnotes", "plan_listing",
    "plan_after", "apply_plan", "plan_template", "as_table_spec",
]


def git_show(path, binary=False):
    out = subprocess.run(["git", "-C", RTFR, "show", f"{REF}:{path}"],
                         capture_output=True, check=True).stdout
    return out if binary else out.decode("utf-8").replace("\r\n", "\n")


def write(rel, text, binary=False):
    p = os.path.join(HERE, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "wb") as f:
        f.write(text if binary else text.encode("utf-8"))


def common(s):
    for fn in MOVED:
        s = re.sub(r"\brtfreporter(:::?)" + fn + r"\b", r"tflspec\g<1>" + fn, s)
    s = s.replace("rtfreporter.ard_pipe", "tflspec.ard_pipe")
    s = s.replace("rtfreporter-ard", "tflspec-ard")
    return s


def cut_block(s, start_pat, end_pat):
    """Remove from the line matching start_pat through the line matching end_pat."""
    m = re.search(start_pat, s, re.M)
    if not m:
        raise SystemExit(f"block start not found: {start_pat}")
    e = re.search(end_pat, s[m.start():], re.M)
    if not e:
        raise SystemExit(f"block end not found: {end_pat}")
    return s[:m.start()] + s[m.start() + e.end():]


ARD_HEADER = """# ============================================================================
#  cards/cardx ARD  ->  table data.frame, and the table / report specs
# ----------------------------------------------------------------------------
#  Moved from rtfreporter (issue #474, branch feat/474-ard-experimental) when
#  the ARD / plan work became its own package.  rtfreporter keeps the
#  renderer; everything here produces what it renders.
"""

PLAN_INTRO = """#  The plan: the ARD conversion written as declarations that are resolved
#  once at the end.  Moved from rtfreporter (#474) with R/ard.R; the two
#  share internals and are one unit.
"""


def port_ard():
    s = git_show("R/ard-experimental.R")
    # the "how to delete this feature" header, down to the DESIGN RULE rule line
    s = cut_block(s, r"\A# =+\n#  EXPERIMENTAL", r"^# -+\n(?=#  DESIGN RULE)")
    s = ARD_HEADER + "# ----------------------------------------------------------------------------\n" + s
    s = s.replace("#  Base R only: no new Imports.  cards / readxl / writexl are optional and\n"
                  "#  reached through requireNamespace(), as everywhere else in this package.\n",
                  "#  cards / readxl / writexl are optional and reached through\n"
                  "#  requireNamespace().\n")
    s = cut_block(s, r"^# The experimental export set\.", r"^  \"read_report_spec\", \"rtf_report\", \"report_path\"\)\n\n?")
    s = s.replace("this rtfreporter reads up to", "this tflspec reads up to")
    s = s.replace("generated by rtfreporter::ard_template()  --  EXPERIMENTAL",
                  "generated by tflspec::ard_template()")
    s = s.replace("#'   `rtfreporter::`-qualified.", "#'   `tflspec::` / `rtfreporter::`-qualified.")
    s = s.replace("# Everything else is `rtfreporter::`-qualified on purpose",
                  "# Everything else is `tflspec::` / `rtfreporter::`-qualified on purpose")
    s = s.replace("#' change, and the family may be withdrawn.  Nothing else in \\pkg{rtfreporter}\n"
                  "#' depends on them.",
                  "#' change.")
    return common(s)


def port_plan():
    s = git_show("R/ard-plan-spike.R")
    s = s.replace("#  SPIKE -- a deferred, last-wins plan for the ARD half (#474)",
                  "#  A deferred, last-wins plan for the ARD half (#474)")
    s = cut_block(s, r"^#  This file is a PROTOTYPE", r"^#  package is exactly what it was\.\n")
    s = s.replace("# ============================================================================\n#\n",
                  "# ============================================================================\n#\n" + PLAN_INTRO + "#\n", 1)
    s = cut_block(s, r"^#  Deleting this file removes:\n", r"^  \"plan_after\", \"apply_plan\", \"plan_template\", \"as_table_spec\"\)\n")
    s = s.replace("generated by rtfreporter::plan_template()  --  SPIKE",
                  "generated by tflspec::plan_template()")
    s = s.replace('paste0("  rtfreporter::", verb', 'paste0("  tflspec::", verb')
    return common(s)


def port_test(path):
    s = git_show(path)
    s = s.replace("rtfreporter:::", "tflspec:::")
    s = s.replace('package = "rtfreporter"', 'package = "tflspec"')
    return common(s)


def port_data_raw(path):
    s = git_show(path)
    s = s.replace('file.exists("R/ard-experimental.R")', 'file.exists("R/ard.R")')
    s = s.replace('file.exists("R/ard-plan-spike.R")', 'file.exists("R/plan.R")')
    s = s.replace('    pkgload::load_all(".", quiet = TRUE)\n',
                  '    library(rtfreporter)\n    pkgload::load_all(".", quiet = TRUE)\n')
    s = s.replace('    library(rtfreporter)\n  }', '    library(rtfreporter)\n    library(tflspec)\n  }')
    s = s.replace("# The spike lives on this branch, so load the SOURCE",
                  "# Load the SOURCE")
    return common(s)


def main():
    write("R/ard.R", port_ard())
    write("R/plan.R", port_plan())
    write("tests/testthat/test-ard.R", port_test("tests/testthat/test-ard-experimental.R"))
    write("tests/testthat/test-plan.R", port_test("tests/testthat/test-ard-plan-spike.R"))

    ls = subprocess.run(["git", "-C", RTFR, "ls-tree", "-r", "--name-only", REF,
                         "inst/extdata/ard-spec", "data-raw/ard-plan-spike",
                         "data-raw/ard-spec-examples", "data-raw/ard-spec-local"],
                        capture_output=True, check=True, text=True).stdout.split()
    for p in ls:
        if p.endswith(".R"):
            write(p, port_data_raw(p))
        else:
            write(p, git_show(p, binary=True), binary=True)
    print(f"ported from {REF}: R/ard.R R/plan.R, 2 test files, {len(ls)} data files")


if __name__ == "__main__":
    main()
